import { readFile, readdir } from "node:fs/promises";
import { join } from "node:path";

import { runTransaction } from "./transaction.js";
import type { ConnectionPool, Logger, TransactionClient } from "../types.js";

type MigrationDirectory = string | URL;

interface MigrationDirectoryEntry {
  name: string;
  isFile(): boolean;
}

type ReadDirectory = (
  directory: MigrationDirectory,
  options: { withFileTypes: true },
) => Promise<MigrationDirectoryEntry[]>;

type ReadMigration = (
  path: MigrationDirectory,
  encoding: "utf8",
) => Promise<string>;

export interface Migration {
  version: number;
  name: string;
  sql: string;
}


export interface MigrationResult {
  appliedCount: number;
  existingCount: number;
}


const MIGRATION_FILE_PATTERN = /^(\d+)_([a-z0-9_]+)\.sql$/;
const IDENTIFIER_PATTERN = /^[a-z][a-z0-9_]{0,62}$/;
const ADVISORY_LOCK_NAMESPACE = "nutritrack-migrations";

export class MigrationDefinitionError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "MigrationDefinitionError";
  }
}

function assertNoTransactionControl(sql: string, filename: string): void {
  const withoutComments = sql
    .replace(/\/\*[\s\S]*?\*\//g, " ")
    .replace(/--.*$/gm, " ");

  if (/\b(?:BEGIN|COMMIT)\b/i.test(withoutComments)) {
    throw new MigrationDefinitionError(
      `Migration ${filename} must not control its own transaction.`,
    );
  }
}

export function quoteInternalIdentifier(identifier: string): string {
  if (!IDENTIFIER_PATTERN.test(identifier)) {
    throw new MigrationDefinitionError("Invalid internal database schema name.");
  }

  // The identifier is generated by trusted code and validated before quoting.
  // PostgreSQL parameters cannot substitute schema/table identifiers.
  return `"${identifier}"`;
}

function resolveMigrationPath(
  directory: MigrationDirectory,
  filename: string,
): MigrationDirectory {
  return directory instanceof URL
    ? new URL(filename, directory)
    : join(directory, filename);
}

export async function discoverMigrations(
  directory: MigrationDirectory,
  {
    readDirectory = (path, options) => readdir(path, options),
    readMigration = (path, encoding) => readFile(path, encoding),
  }: { readDirectory?: ReadDirectory; readMigration?: ReadMigration } = {},
): Promise<Migration[]> {
  const directoryEntries = await readDirectory(directory, {
    withFileTypes: true,
  });
  const versions = new Set<number>();
  const migrations: Migration[] = [];

  for (const entry of directoryEntries) {
    if (!entry.isFile() || !entry.name.endsWith(".sql")) {
      continue;
    }

    const match = MIGRATION_FILE_PATTERN.exec(entry.name);
    if (!match) {
      throw new MigrationDefinitionError(
        `Invalid migration filename: ${entry.name}.`,
      );
    }

    const version = Number(match[1]);
    if (!Number.isSafeInteger(version) || version <= 0 || versions.has(version)) {
      throw new MigrationDefinitionError(
        `Migration version ${match[1]} is invalid or duplicated.`,
      );
    }
    if (entry.name.length > 200) {
      throw new MigrationDefinitionError(
        "Migration filename exceeds 200 characters.",
      );
    }

    const sql = await readMigration(
      resolveMigrationPath(directory, entry.name),
      "utf8",
    );
    assertNoTransactionControl(sql, entry.name);
    versions.add(version);
    migrations.push({ version, name: entry.name, sql });
  }

  return migrations.sort((left, right) => left.version - right.version);
}

function validateAppliedMigrations(
  appliedRows: Record<string, unknown>[],
  migrations: Migration[],
): void {
  const filesByVersion = new Map(
    migrations.map((migration) => [migration.version, migration]),
  );
  const filesByName = new Map(
    migrations.map((migration) => [migration.name, migration]),
  );

  for (const row of appliedRows) {
    const version = Number(row.version);
    const versionFile = filesByVersion.get(version);
    if (typeof row.name !== "string") {
      throw new MigrationDefinitionError(
        `Migration history has an invalid name for version ${version}.`,
      );
    }
    const nameFile = filesByName.get(row.name);

    if (!versionFile || versionFile.name !== row.name) {
      throw new MigrationDefinitionError(
        `Migration history does not match file version ${version}.`,
      );
    }
    if (!nameFile || nameFile.version !== version) {
      throw new MigrationDefinitionError(
        `Migration history does not match stored migration name for version ${version}.`,
      );
    }
  }
}

export async function runMigrations(
  {
    pool,
    migrations,
    schema = "public",
    logger = console,
    lockTimeoutMillis = 5_000,
  }: {
    pool: ConnectionPool;
    migrations: Migration[];
    schema?: string;
    logger?: Logger;
    lockTimeoutMillis?: number;
  },
): Promise<MigrationResult> {
  const quotedSchema = quoteInternalIdentifier(schema);
  const client = await pool.connect();
  let lockAcquired = false;
  let unusable = false;

  try {
    await client.query("SELECT set_config('search_path', $1, false)", [
      quotedSchema,
    ]);
    await client.query("SELECT set_config('lock_timeout', $1, false)", [
      `${lockTimeoutMillis}ms`,
    ]);
    await client.query(
      "SELECT pg_advisory_lock(hashtext($1), hashtext($2))",
      [ADVISORY_LOCK_NAMESPACE, schema],
    );
    lockAcquired = true;

    await client.query(`
      CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY
          CONSTRAINT schema_migrations_version_positive CHECK (version > 0),
        name VARCHAR(200) NOT NULL UNIQUE
          CONSTRAINT schema_migrations_name_nonblank CHECK (btrim(name) <> ''),
        applied_at TIMESTAMPTZ NOT NULL DEFAULT now()
      )
    `);

    const appliedResult = await client.query(
      "SELECT version, name FROM schema_migrations ORDER BY version",
    );
    validateAppliedMigrations(appliedResult.rows, migrations);
    const appliedVersions = new Set(
      appliedResult.rows.map((row) => Number(row.version)),
    );
    let appliedCount = 0;

    for (const migration of migrations) {
      if (appliedVersions.has(migration.version)) {
        continue;
      }

      await runTransaction(
        client,
        async (transactionClient: TransactionClient) => {
          // The SQL and its metadata row commit together; a failure leaves
          // neither partial schema changes nor a falsely recorded version.
          await transactionClient.query(migration.sql);
          await transactionClient.query(
            "INSERT INTO schema_migrations (version, name) VALUES ($1, $2)",
            [migration.version, migration.name],
          );
        },
        {
          markClientUnusable() {
            unusable = true;
          },
        },
      );
      appliedCount += 1;
      logger.log(`Applied migration ${migration.version}: ${migration.name}`);
    }

    return {
      appliedCount,
      existingCount: appliedResult.rows.length,
    };
  } finally {
    if (lockAcquired && !unusable) {
      try {
        await client.query(
          "SELECT pg_advisory_unlock(hashtext($1), hashtext($2))",
          [ADVISORY_LOCK_NAMESPACE, schema],
        );
      } catch {
        unusable = true;
      }
    }
    client.release(
      unusable ? new Error("Discarding unusable migration client.") : undefined,
    );
  }
}
